export default function About() {
  return (
    <main className="min-h-screen pt-28 px-8 pb-16">
      <div className="max-w-3xl mx-auto space-y-12">
        <div className="space-y-8">
          <div>
            <h1 className="text-4xl font-semibold text-primary mb-4">
              About AI Imagine
            </h1>
            <p className="text-text/90 leading-relaxed">
              Transform your imagination into stunning visuals with our AI-powered image generator. 
              Simply describe what you want to see, and watch as artificial intelligence brings your ideas to life.
            </p>
          </div>
          
          <div>
            <h2 className="text-2xl font-medium text-accent mb-3">
              How it Works
            </h2>
            <p className="text-text/90 leading-relaxed">
              Our platform uses advanced AI models to understand your text descriptions 
              and generate corresponding images. The technology combines natural language 
              processing with image generation to create unique, customized visuals that 
              match your imagination.
            </p>
          </div>
          
          <div>
            <h2 className="text-2xl font-medium text-accent mb-3">
              Features
            </h2>
            <ul className="space-y-3 text-text/90">
              <li className="flex items-start gap-3">
                <i className="fas fa-wand-magic-sparkles text-primary mt-1"></i>
                <span>High-quality image generation from text descriptions</span>
              </li>
              <li className="flex items-start gap-3">
                <i className="fas fa-bolt text-primary mt-1"></i>
                <span>Fast processing and immediate results</span>
              </li>
              <li className="flex items-start gap-3">
                <i className="fas fa-download text-primary mt-1"></i>
                <span>Easy download and sharing options</span>
              </li>
              <li className="flex items-start gap-3">
                <i className="fas fa-images text-primary mt-1"></i>
                <span>Gallery to showcase and browse generated images</span>
              </li>
            </ul>
          </div>
        </div>

        <div>
          <h2 className="text-2xl font-medium text-accent mb-6">
            Frequently Asked Questions
          </h2>
          <div className="space-y-6">
            <div>
              <h3 className="text-lg font-medium text-primary mb-2">
                Is this service free to use?
              </h3>
              <p className="text-text/90">
                Yes, our service is completely free to use. You can generate, enhance, and download images without any cost.
              </p>
            </div>

            <div>
              <h3 className="text-lg font-medium text-primary mb-2">
                What types of images can I generate?
              </h3>
              <p className="text-text/90">
                You can generate a wide variety of images including landscapes, portraits, abstract art, and conceptual illustrations. Just describe what you want to see!
              </p>
            </div>

            <div>
              <h3 className="text-lg font-medium text-primary mb-2">
                How long does it take to generate an image?
              </h3>
              <p className="text-text/90">
                Most images are generated within 10-15 seconds, depending on the complexity of your description and server load.
              </p>
            </div>

            <div>
              <h3 className="text-lg font-medium text-primary mb-2">
                Can I download and use the generated images?
              </h3>
              <p className="text-text/90">
                Yes, you can download and use the generated images. However, please note that the images are generated by AI and may be subject to certain usage restrictions.
              </p>
            </div>

            <div>
              <h3 className="text-lg font-medium text-primary mb-2">
                What is the image upscaling feature?
              </h3>
              <p className="text-text/90">
                Our upscaling feature enhances the resolution and quality of generated images, making them sharper and more detailed for better viewing or printing.
              </p>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
} 